{
    'name': 'yousentech_wo_v4',
    'version': '17.0.1.0',
    'summary': 'Car Film System version 4',
    'description': 'Manage Car Film System.',
    'category': 'Tools',
    'author': 'Generated by Yousentech Team',
    'depends': ['base', 'account',  'sale','stock'],
    'data': [ 'security/security.xml',
              'security/ir.model.access.csv',
                'setup_wizard/main_menu_action.xml',
                'setup_wizard/setup_wizard_view.xml',
                'setup_wizard/res_config_settings_view.xml',

              'setup_views/service_type_view.xml',
              
            #   'setup_views/film_parts_lines_view.xml',

              'setup_views/product_template_view.xml',
              'setup_views/film_category_view.xml',
 
              'setup_views/car_size_view.xml',
              'setup_views/cart_part.xml',
              'setup_views/cart_part_wizard.xml',
              
              'setup_views/car_type_view.xml',
              'setup_views/car_manufactory_year_view.xml',
              'setup_views/car_agency_view.xml',
    ],
    'assets': {
                'web.assets_backend': [
                    # ملفاتك السابقة
                    'yousentech_wo_v4/static/src/css/kanban.css',
                ],
            },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
