{
    'name': 'yousentech_wo_v4',
    'version': '17.0.1.0',
    'summary': 'Car Film System version 4',
    'description': 'Manage Car Film System.',
    'category': 'Tools',
    'author': 'Generated by Yousentech Team',
    'depends': ['base', 'account',  'sale'],
    'data': [ 'security/security.xml',
              'security/ir.model.access.csv',
            
              'setup_views/service_type_view.xml',
              'setup_views/film_category_view.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
