{
    'name': 'Yousentech Car Care',
    'version': '17.0.4.0.67',
    'summary': 'Self-service setup and installation orders for car care centers',
    'description': 'Foundation, self-service setup and installation order workflow for car care operations.',
    'category': 'Services',
    'author': 'Yousentech Team',
    'depends': [
        'base',
        'mail',
        'product',
        'account',
        'sale',
        'stock',
        'hr',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'setup_wizard/setup_templates.xml',
        'data/installation_order_sequence.xml',
        'setup_wizard/main_menu_action.xml',
        'setup_wizard/activity_hub_view.xml',
        'setup_wizard/film_setup_wizard_view.xml',
        'setup_wizard/setup_wizard_view.xml',
        'setup_views/service_type_view.xml',
        'setup_views/film_parts_lines_view.xml',
        'setup_views/product_template_view.xml',
        'setup_views/film_category_view.xml',
        'setup_views/car_size_view.xml',
        'setup_views/car_part_options_view.xml',
        'setup_views/cart_part.xml',
        'setup_views/car_manufactory_view.xml',
        'setup_views/car_type_view.xml',
        'setup_views/car_manufactory_year_view.xml',
        'setup_views/car_agency_view.xml',
        'views/installation_order_views.xml',
        'views/hr_employee_views.xml',
        'setup_wizard/setup_center_menu.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'yousentech_wo_v4/static/src/css/setup_wizard.css',
            'yousentech_wo_v4/static/src/css/service_architecture.css',
            'yousentech_wo_v4/static/src/css/installation_order.css',
        ],
    },
    'pre_init_hook': 'pre_init_hook',
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
